title: "Metin Zorlu"
name: "Buhara"
email: metinzorlu@msn.com
description: "Kişisel Blog Sayfası"
info: "Bu Site Hakkında"
quotes: "Güzel Sözler"
buttonTitle: "Diğer Yazılar"
nPosts: "Yeni Yazılar"

baseurl: "https://mtnzorlu.github.io" 
url: ""

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  
paginate: 3

paginate_path: "blog/page:num/"

feed:
  title: "Metin Zorlu"
  description: "Kişisel blog"
  name: "feed.xml"

markdown: kramdown
kramdown:
input: GFM
syntax_highlighter: rouge
remote_theme: mtnzorlu/buhara

# navmenu
mTitle: Ana Sayfa
atitle: Hakkında
aurl: /about
btitle: Çalışmalar
burl: /works
ctitle: Blog
curl: /blog
